"""
Introdução ao try/except
try -> tentar executar o código
except -> ocorreu algum erro ao tentar executar
"""

# print(1234)
# print(456)
# int('A')

numero = input("Vou dobrar o numero digitado: ")

numero_float = float(numero)
print(f"O dobro de {numero_float} é {numero_float * 2}")
